name: 'tiktok_ads_source_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

vars: 
  tiktok_ads_source:
    ad_group_history: "{{ ref('tiktok_ad_group_history') }}"
    ad_history: "{{ ref('tiktok_ad_history') }}"
    advertiser: "{{ ref('tiktok_advertiser') }}"
    campaign_history: "{{ ref('tiktok_campaign_history') }}"

  #  change to data file names 

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']